### ISSUE TITLE
Add a Profile picture 

### ISSUE THREAD

**Issue by Aniket762** [betaoverflow/project-betachat#2]
When the user logs in and gets into the chat arena. Give an option in the navbar of the dashboard where the user can modify his/her profile details and upload a profile picture. If not in the navbar you can also create a private route with localhost:3000/dashboard so that later we can add a button somewhere which can be redirected to the dashboard page. In addition to that, if possible the profile picture to be shown in the App bar beside the name.
![chatscreen](https://user-images.githubusercontent.com/67703407/116246183-601f0000-a787-11eb-84c9-72314710d3c2.png)

Feel free to ask if the issue is not clear. And do attach the screenshot when you send a Pull Request.

**Comment by iampratikdeo** [comment]
I'd like to take this issue.
